import { chromium } from 'playwright';
const B = 'http://127.0.0.1:3000';
const browser = await chromium.launch();
const mob = await (await browser.newContext({ viewport: { width: 390, height: 844 } })).newPage();
await mob.goto(B + '/', { waitUntil: 'load' });
await mob.waitForTimeout(4200);
await mob.screenshot({ path: 'shots/i-mobile-hero.png' });
await mob.locator('.nav-toggle').click();
await mob.waitForTimeout(900);
await mob.screenshot({ path: 'shots/j-mobile-menu.png' });
await mob.keyboard.press('Escape');
await mob.waitForTimeout(800);
await mob.evaluate(() => document.querySelector('#work').scrollIntoView({ behavior: 'instant' }));
await mob.waitForTimeout(1500);
await mob.screenshot({ path: 'shots/k-mobile-work.png' });
const desk = await (await browser.newContext({ viewport: { width: 1440, height: 900 } })).newPage();
await desk.goto(B + '/', { waitUntil: 'load' });
await desk.waitForTimeout(1000);
await desk.screenshot({ path: 'shots/a-intro-mid.png' });
await desk.waitForTimeout(3200);
await desk.evaluate(() => window.scrollTo({ top: document.body.scrollHeight, behavior: 'instant' }));
await desk.waitForTimeout(1800);
await desk.screenshot({ path: 'shots/f-cta-footer.png' });
await browser.close();
console.log('shots done');
